name: Continuous Integration Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          set -e
          set -x
          echo "Upgrading pip"
          python -m pip install --upgrade pip
          echo "Installing required packages"
          pip install torch psutil numpy
          if [ -f requirements.txt ]; then
            echo "Installing dependencies from requirements.txt"
            pip install -r requirements.txt
          fi
          echo "Verifying installations"
          pip show pytest torch psutil numpy

      - name: Run Tests
        run: |
          set -e
          set -x
          echo "Running tests with pytest"
          pytest
