name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false

    - name: Create Conda environment
      run: conda env create -f pvp-ml/environment.yml

    - name: Activate Conda environment
      run: echo "conda activate pvp"

    - name: Install additional dependencies
      run: |
        source ~/conda/bin/activate pvp
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install pre-commit hooks
      run: |
        source ~/conda/bin/activate pvp
        pre-commit install
        pre-commit run --all-files

    - name: Run tests with coverage
      run: |
        source ~/conda/bin/activate pvp
        pip install pytest-cov
        pytest --cov=src --cov-report=xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml

    - name: Deploy to cluster (if needed)
      run: |
        if [[ -f pvp-ml/cluster.yml ]]; then
          echo "Setting up and deploying to cluster"
          # Add cluster deployment commands here
        else
          echo "No cluster configuration found, skipping cluster deployment"
        fi
