name: test
on: push
jobs: 
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: pvp-ml/environment.yml
    - run: cd pvp-ml && pre-commit run --all-files --show-diff-on-failure
      shell: bash -l {0}
    - run: cd pvp-ml && mypy pvp_ml test --config=setupl.cfg
      shell: bash -l {0}
    - run: cd simulation-rsps/ElvargServer && chmod +x ./gradlew && ./gradlew check
      shell: bash -l {0}
    - run: cd pvp-ml && pytest ./test/unit/
      shell: bash -l {0}
    - run: cd pvp-ml && pytest ./test/integration/
      shell: bash -l {0}
